// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderRobot.Data.Contexts;

namespace OrderRobot.Data.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20220219135531_InitSecond")]
    partial class InitSecond
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("OrderRobot.Data.Model.DomainClass.Operation", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RobotTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecordId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("OrderRobot.Data.Model.DomainClass.RobotTask", b =>
                {
                    b.Property<int>("RobotTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("RobotTaskId");

                    b.ToTable("RobotTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
